# 256x192_res50_lr1e-3_1x-simple
DATASET:
  TRAIN:
    TYPE: 'Mpii'
    ROOT: './data/mpii/'
    IMG_PREFIX: 'images'
    ANN: 'annot_mpii.json'
    AUG:
      FLIP: true
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: -1
  VAL:
    TYPE: 'Mpii'
    ROOT: './data/mpii/'
    IMG_PREFIX: 'images'
    ANN: 'annot_mpii.json'
  TEST:
    TYPE: 'Mpii'
    ROOT: './data/mpii/'
    IMG_PREFIX: 'images'
    DET_FILE: './exp/json/test_det_yolo.json'
    ANN: 'annot_mpii.json'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 16
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48
MODEL:
  TYPE: 'SimplePose'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: '/baselines/AlphaPose/detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: '/baselines/AlphaPose/detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.1
TRAIN:
  WORLD_SIZE: 4
  BATCH_SIZE: 256
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  OPTIMIZER: 'adam'
  LR: 0.008
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120
  DPG_MILESTONE: 140
  DPG_STEP:
  - 160
  - 190